name: Basic unit tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang-19 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev build-essential cmake

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure
